export PATH=/usr/local/rvm/bin:$PATH
export GREP_OPTIONS='--color=auto'
export GIT_PS1_SHOWDIRTYSTATE=1

alias ls="ls -ap --color=auto"

source /etc/bash_completion.d/git
PS1='\[\e[0;34m\]\w\[\e[m\] \[\033[31m\]$(__git_ps1 "%s ")\[\033[00m\]'
