---
- hosts: localhost
  gather_facts: no

  vars:
    ruby: 2.1.0
    username: vagrant

  tasks:
    - include: tasks/apt.yml
    - include: tasks/shell.yml
    - include: tasks/dotfiles.yml
    - include: tasks/ruby.yml
    - include: tasks/heroku.yml
    - include: tasks/postgresql.yml
